[General]
; Wait time in seconds before finding the window.
Wait=50

; Moves the window only.
TransmitTheWindow=0

; Ignores Width/Height/PosX/PosY below and locks to current window state.
GetWindowDimensionsThenSet=0

; `DontGetSize` and `DontGetPosition` only used if GetWindowDimensionsThenSet=1
; Don't get the window dimensions (use from INI instead)
DontGetSize=0
DontGetPosition=0

; Set manual window dimensions.
Width=0
Height=0
PosX=0
PosY=0

[FindWindow]
; Leave empty to auto-detect the main window
WindowName=
ClassName=

[Hooks]
; Set to 1 to enable specific hooks
SetWindowPos=0
MoveWindow=0
AdjustWindowRect=0